### ISSUE TITLE
Reader is not imported 

### ISSUE THREAD

**Issue by orangec-at** [vhodiak/flutter_ddd_riverpod_example#3]
There is an error like this.

Undefined class 'Reader'.
Try changing the name to the name of an existing class, or creating a class with the name 'Reader'.dart[undefined_class](https://dart.dev/diagnostics/undefined_class)

I think riverpod Reader is deprecated. so we cannot find it.

How can I fix this ?

(Sorry for making issue. I am new to flutter.
It will be so helpful if you answer. thanks :) )

**Comment by greedy-brady** [comment]
code
```dart
final Readre _read;
  AuthRepository get _repository => _read(authRepositoryProvider);
```

**Comment by eugenemartseniuk** [comment]
What you can to is either pass ProviderRef ref and use ref.read, or pass the instance of AuthRepository itself from provider initialization

**Comment by s9th** [comment]
The code has been updated to remove reader and use latest Riverpod version
